<?php
$form = $this->form;
$elements = $form->getElements ();
$total_element = count ( $elements );
if ($total_element > 0) {
	$button = array ();
	echo $this->form ()->openTag ( $form ) . "\n";
	echo '		<table class="form">' . "\n";
	foreach ( $elements as $element_key => $element ) {
		$field = $form->get ( $element_key );
		if ($field instanceof \Zend\Form\ElementInterface) {
			$field = $form->get ( $element_key );
			$type = $field->getAttribute ( 'type' );
			$label = $field->getLabel ();
			$isHide = $field->getAttribute ( 'is_hide' );
			$showLabel = $field->getAttribute ( 'show_label' );
			$isRequire = $field->getAttribute ( 'is_require' );
			$isDisplay = $field->getAttribute ( 'is_display' );
			
			$noMessage = false;
			if (in_array ( $type, array (
					'button',
					'submit' 
			) )) {
				$button [$element_key] = $element;
			} else {
				$isHidden = false;
				if ($type == 'hidden') {
					$isHidden = true;
				}
				if ($type == 'paragraph') {
					$noMessage = true;
				}
				
				$renderLabel = null;
				$isElement = false;
				if (! in_array ( $type, array (
						'button',
						'hidden',
						'submit',
						'seperator' 
				) )) {
					if (! empty ( $label )) {
						if (empty ( $showLabel ) && ! $showLabel) {
							$renderLabel = '			<td class="label">' . ($isDisplay ? $this->formLabelDisplay ( $element ) : $this->formLabel ( $element )) . '&nbsp;:' . ($isRequire ? '<span class="required">*</span>' : null) . '</td>' . "\n";
						} else {
							$renderLabel = '			<td ></td>' . "\n";
						}
					} else {
						$renderLabel = '			<td >' . $label . '</td>' . "\n";
					}
					$isElement = true;
				} elseif (in_array ( $type, array (
						'button',
						'submit' 
				) )) {
					$renderLabel = '			<td ></td>' . "\n";
					$isElement = true;
				}
				
				$messageTemplates = null;
				$renderElement = null;
				$messageTemplates = $form->getMessageTemplates ( $element->getName () );
				
				$renderElement = '			<td' . (! $noMessage && ! $isHidden && count ( $messageTemplates ) > 0 ? ' title="* ' . implode ( "<br>* ", $messageTemplates ) . '"' : null) . '' . ($isElement ? ' class="element"' : '') . (! $isElement ? ' colspan="3"' : ($noMessage ? ' colspan="2"' : null)) . '>' . "\n";
				$renderElement .= '				' . call_user_func_array ( array (
						$this,
						'form' . ucfirst ( $type ) 
				), array (
						$element 
				) ) . "\n";
				$renderElement .= '			</td>' . "\n";
				
				$renderMessage = null;
				if (! $noMessage && $isElement) {
					$renderMessage = '			<td class="help">' . "\n";
					$renderMessage .= '				<div class="ui-widget"><div class="ui-state-active"></div></div>' . "\n";
					$renderMessage .= '			</td>' . "\n";
				}
				echo '		<tr' . ($isHide ? ' style="display: none;"' : null) . ' class="' . ($type == "seperator" ? 'seperator' : 'row') . '"' . ($isDisplay ? '' : ' id="' . $element_key . '"') . '>' . "\n";
				echo $renderLabel;
				echo $renderElement;
				echo $renderMessage;
				echo '		</tr>' . "\n";
			}
		}
	}
	if (is_array ( $button ) && count ( $button ) > 0) {
		echo '<tr class="row" id="button">' . "\n";
		echo '	<td ></td>' . "\n";
		echo '	<td colspan="2">' . "\n";
		foreach ( $button as $element_key => $element ) {
			$field = $form->get ( $element_key );
			if ($field instanceof \Zend\Form\ElementInterface) {
				$type = $field->getAttribute ( 'type' );
				echo call_user_func_array ( array (
						$this,
						'form' . ucfirst ( $type ) 
				), array (
						$element 
				) ) . "\n";
			}
		}
		echo '	</td>' . "\n";
		echo '</tr>' . "\n";
	}
	echo '		</table>' . "\n";
	echo $this->form ()->closeTag () . "\n";
}
?>