<?php
$searchform = $this->searchform;
echo $this->form ()->openTag ( $searchform ) . "\n";
?><table class="form">
	<tr class="row"><?php
	$search = $searchform->get ( 'search_username' );
	?><td class="label"><?php
	echo $this->formLabel ( $search ) . '&nbsp;:<span class="required">*</span>';
	
	?></td>
		<td class="element"><?php
		echo $this->formText ( $search );
		?></td><?php
		$button = $searchform->get ( 'button_search' );
		?><td class="button"><?php
		echo $this->formButton ( $button );
		?></td>
	</tr>
	<tr class="row">
		<td></td>
		<td class="help" colspan="2">
			<div class="ui-widget">
				<div class="ui-state-active"></div>
			</div>
		</td>
	</tr>
</table><?php
echo $this->form ()->closeTag ( $searchform ) . "\n";
?>
