<?php
$search = $this->search;
$searchdata = array ();
if (is_array ( $search ) && count ( $search ) > 0) {
	foreach ( $search as $searchvalue ) {
		$element = $searchvalue ['element'];
		$attributes = $element->getAttributes ();
		$elementRender = call_user_func_array ( array (
				$this,
				'form' . ucfirst ( $attributes ['type'] ) 
		), array (
				$element 
		) );
		$elementLabel = $this->formLabel ( $element ) . ': ';
		if ($searchvalue ['flag'] == 1) {
			$searchdata [$searchvalue ['column']] ['label'] = $elementLabel . "\n";
			$searchdata [$searchvalue ['column']] ['input'] = $elementRender . "\n";
		}
	}
}
?>
<form id="searchsimple">
	<table class="form">
		<tr>
			<td class="label"><?php echo $searchdata['user_access_username']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_access_username']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_profile_fullname']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_profile_fullname']['input']; ?></td>
			<td style="width: auto;"></td>
		</tr>
		<tr>
			<td colspan="5" style="text-align: center;"><button type="button"
					id="simplebutton" class="button">Search</button></td>
		</tr>
	</table>
</form>