<?php
$search = $this->search;
$searchdata = array();
if (is_array($search) && count($search) > 0) {
	foreach ($search as $searchvalue) {
		$element = $searchvalue['element'];
		$attributes = $element->getAttributes();
		$elementRender = call_user_func_array(array(
				$this,
				'form' . ucfirst($attributes['type'])
		), array(
				$element
		));
		$elementLabel = $this->formLabel($element) . ': ';
		$searchdata[$searchvalue['column']]['label'] = $elementLabel . "\n";
		$searchdata[$searchvalue['column']]['input'] = $elementRender . "\n";
	}
}
?>
<form id="searchadvance">
<table class="form">
<tr>
	<td class="label"><?php echo $searchdata['user_access_username']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_username']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_fullname']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_fullname']['input']; ?></td>
	<td rowspan="14" style="width: auto;"></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_access_status_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_status_text']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_rank_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_rank_text']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_access_no_of_login']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_no_of_login']['input']; ?></td>
	<td colspan="2"></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_access_last_login_ip']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_last_login_ip']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_access_last_login_date_format']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_last_login_date_format']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_access_created_by']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_created_by']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_access_created_date_format']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_access_created_date_format']['input']; ?></td>
</tr>
<tr>
	<td colspan="5"><div class="seperator"></div></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_hierarchy_sponsor_username']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_hierarchy_sponsor_username']['input']; ?></td>
	<td colspan="2"></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_hierarchy_placement_username']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_hierarchy_placement_username']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_hierarchy_placement_position_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_hierarchy_placement_position_text']['input']; ?></td>
</tr>
<tr>
	<td colspan="5"><div class="seperator"></div></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_designation_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_designation_text']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_dob_format']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_dob_format']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_gender_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_gender_text']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_nationality_text']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_nationality_text']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_nric_passport']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_nric_passport']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_email_address']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_email_address']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_office_no']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_office_no']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_telephone_no']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_telephone_no']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_fax_no']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_fax_no']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_mobile_no']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_mobile_no']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_modified_by']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_modified_by']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_modified_date_format']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_modified_date_format']['input']; ?></td>
</tr>
<tr>
	<td class="label"><?php echo $searchdata['user_profile_created_by']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_created_by']['input']; ?></td>
	<td class="label"><?php echo $searchdata['user_profile_created_date_format']['label']; ?></td>
	<td class="field"><?php echo $searchdata['user_profile_created_date_format']['input']; ?></td>
</tr>
<tr>
	<td colspan="5" style="text-align: center;"><button type="button" id="advancebutton" class="button">Search</button></td>
</tr>
</table>
</form>