<?php
$image = $this->image;
if (! empty ( $image ) && file_exists ( $image )) {
	$fileinfo = pathinfo ( $image );
	$contenttype = null;
	switch ($fileinfo ['extension']) {
		case 'bmp' :
			$contenttype = 'image/bmp';
			break;
		case 'cod' :
			$contenttype = 'image/cis-cod';
			break;
		case 'gif' :
			$contenttype = 'image/gif';
			break;
		case 'ief' :
			$contenttype = 'image/ief';
			break;
		case 'jpe' :
			$contenttype = 'image/jpeg';
			break;
		case 'jpeg' :
			$contenttype = 'image/jpeg';
			break;
		case 'jpg' :
			$contenttype = 'image/jpeg';
			break;
		case 'png' :
			$contenttype = 'image/png';
			break;
		case 'jfif' :
			$contenttype = 'image/pipeg';
			break;
		case 'svg' :
			$contenttype = 'image/svg+xml';
			break;
		case 'tif' :
			$contenttype = 'image/tiff';
			break;
		case 'tiff' :
			$contenttype = 'image/tiff';
			break;
		case 'ras' :
			$contenttype = 'image/x-cmu-raster';
			break;
		case 'cmx' :
			$contenttype = 'image/x-cmx';
			break;
		case 'ico' :
			$contenttype = 'image/x-icon';
			break;
		case 'pnm' :
			$contenttype = 'image/x-portable-anymap';
			break;
		case 'pbm' :
			$contenttype = 'image/x-portable-bitmap';
			break;
		case 'pgm' :
			$contenttype = 'image/x-portable-graymap';
			break;
		case 'ppm' :
			$contenttype = 'image/x-portable-pixmap';
			break;
		case 'rgb' :
			$contenttype = 'image/x-rgb';
			break;
		case 'xbm' :
			$contenttype = 'image/x-xbitmap';
			break;
		case 'xpm' :
			$contenttype = 'image/x-xpixmap';
			break;
		case 'xwd' :
			$contenttype = 'image/x-xwindowdum';
			break;
	}
	header ( 'Cache-Control: no-cache, must-revalidate' );
	header ( 'Expires: ' . $this->expire );
	header ( 'Content-Type: ' . $contenttype );
	echo file_get_contents ( $image );
}
