<?php
$success = $this->success;
if ($success) {
    $content = $this->content;
    ?>
<div id="<?php echo $this->id; ?>"
	class="ui-layout-boxes ui-widget ui-corner-all <?php echo $this->id; ?>">
	<div class="ui-layout-boxes-content ui-widget-content ui-corner-all"><?php
    ?></div>
	<div class="ui-layout-boxes-footer ui-widget-footer"><?php echo $this->translate($this->title); ?></div>
	<div class="ui-layout-boxes-clear"></div>
</div>
<?php
}
?>