<div class="header"><div><?php echo $this->escapeHtml($this->translate($this->title)); ?></div></div>
<div class="content">
<?php
$form = $this->form;
echo $form->openTag();
?><table class="form">
<?php
$formLabel = $this->plugin('formLabel');
foreach ($form->getElements() as $elements_key => $elements) {
	$field = $form->get($elements_key);
	if (is_object($field)) {
		$attributes = $field->getAttributes();
		$options = $field->getOptions();
?><tr<?php echo ($attributes['is_hidden'] ? ' style="display: none;"' : null) ?> <?php echo (isset($attributes['id']) ? 'id="tr_' . $attributes['id'] . '"' : null); ?>>
<?php
		if (!$attributes['is_seperator']) {
?><td class="label">
<?php
			if (!$attributes['not_show_label']) {
				echo $this->formLabel($field) . ':' . ($attributes['is_require'] ? '<span class="Required">*</span>' : null);
			}
?></td>
<?php
		}
?><td class="field"<?php echo ($attributes['is_seperator'] ? ' colspan="3"' : ($attributes['is_button'] ? ' colspan="2"' : null)) ?>>
<?php
		$messageTemplates = $form->getMessageTemplates($elements_key);
		if (($attributes['is_comment'] && count($attributes['require_comment']) > 0) || count($messageTemplates) > 0) {
?><div class="tooltip"<?php echo 'title="' . (count($attributes['require_comment']) > 0 ? '* ' . implode("<br>* ", $attributes['require_comment']) : null) . (count($messageTemplates) > 0 ? '* ' . implode("<br>* ", $messageTemplates) : null) . '"';
					  ?>>
<?php
							  }
							  if ($attributes['is_captcha']) {
?><div class="captcha">
<?php
		}
		echo call_user_func_array(array(
				$this,
				'form' . ucfirst($attributes['element'])
		), array(
				$field
		));
		if ($attributes['is_captcha']) {
?></div>
<?php
		}
		if ($attributes['is_comment']) {
?></div>
<?php
		}
?></td>
<?php
		if (!$attributes['is_seperator'] && !$attributes['is_button']) {
?><td class="help">
<div class="ui-widget"><div class="ui-state-active">
<?php
			if (count($field->getMessages()) > 0) {
				echo $this->formElementErrors()->setMessageOpenFormat('<span class="ui-icon ui-icon-closethick"></span>')->render($field);
			} elseif (!$attributes['is_seperator'] && count($this->messages) > 0 && !isset($this->messages[$elements_key])) {
				echo '<span class="ui-icon ui-icon-check"></span>';
			}
?></div></div></td>
<?php
		}
?></tr>
<?php
	}
}
?></table>
	 <?php
echo $form->closeTag();
	 ?></div>