<div class="header"><div><?php echo $this->escapeHtml($this->translate($this->title)); ?></div></div>
<div class="content">
	<?php
$form = $this->form;
$form->setAttribute('action', $this->url(null, array(
					'Index'
				)));
$form->prepare();
echo $this->form()->openTag($form);

	?>	
<table border="0" cellspacing="0" cellpadding="0" class="form" style="width: 100%;">
<?php
	$formLabel = $this->plugin('formLabel');
	foreach ($form->getElements() as $elements_key => $elements) {
		$field = $form->get($elements_key);
		if (is_object($field)) {
			$elements = get_class($elements);
			$label = false;
			$seperate = false;
			$view = null;
			switch ($elements) {
				case 'Zend\Form\Element\Button':
					$label = true;
					$view = 'formButton';
					break;
				case 'Zend\Form\Element\Captcha':
					$label = true;
					$view = 'formCaptcha';
					break;
				case 'Zend\Form\Element\Checkbox':
					$label = true;
					$view = 'formCheckbox';
					break;
				case 'Zend\Form\Element\Collection':
					$label = true;
					$view = 'formCollection';
					break;
				case 'Zend\Form\Element\Color':
					$label = true;
					$view = 'formColor';
					break;
				case 'Zend\Form\Element\Csrf':
					$label = true;
					$view = 'formCsrf';
					break;
				case 'Zend\Form\Element\Date':
					$label = true;
					$view = 'formDate';
					break;
				case 'Zend\Form\Element\DateSelect':
					$label = true;
					$view = 'formDateSelect';
					break;
				case 'Zend\Form\Element\DateTime':
					$label = true;
					$view = 'formDateTime';
					break;
				case 'Zend\Form\Element\DateTimeLocal':
					$label = true;
					$view = 'formDateTimeLocal';
					break;
				case 'Zend\Form\Element\DateTimeSelect':
					$label = true;
					$view = 'formDateTimeSelect';
					break;
				case 'Zend\Form\Element\Email':
					$label = true;
					$view = 'formEmail';
					break;
				case 'Zend\Form\Element\File':
					$label = true;
					$view = 'formFile';
					break;
				case 'Zend\Form\Element\Hidden':
					$view = 'formHidden';
					break;
				case 'Zend\Form\Element\Image':
					$label = true;
					$view = 'formImage';
					break;
				case 'Zend\Form\Element\Month':
					$label = true;
					$view = 'formMonth';
					break;
				case 'Zend\Form\Element\MonthSelect':
					$label = true;
					$view = 'formMonthSelect';
					break;
				case 'Zend\Form\Element\MultiCheckbox':
					$label = true;
					$view = 'formMultiCheckbox';
					break;
				case 'Zend\Form\Element\Number':
					$label = true;
					$view = 'formNumber';
					break;
				case 'Zend\Form\Element\Password':
					$label = true;
					$view = 'formPassword';
					break;
				case 'Zend\Form\Element\Radio':
					$label = true;
					$view = 'formRadio';
					break;
				case 'Zend\Form\Element\Range':
					$label = true;
					$view = 'formRange';
					break;
				case 'Zend\Form\Element\Select':
					$label = true;
					$view = 'formSelect';
					break;
				case 'Zend\Form\Element\Submit':
					$view = 'formSubmit';
					break;
				case 'Zend\Form\Element\Text':
					$label = true;
					$view = 'formText';
					break;
				case 'Zend\Form\Element\Textarea':
					$label = true;
					$view = 'formTextarea';
					break;
				case 'Zend\Form\Element\Time':
					$label = true;
					$view = 'formTime';
					break;
				case 'Zend\Form\Element\Url':
					$label = true;
					$view = 'formUrl';
					break;
				case 'Zend\Form\Element\Week':
					$label = true;
					$view = 'formWeek';
					break;
				case 'Zend\Form\Element\Display':
					$view = 'formDisplay';
					$seperate = true;
					break;
			}
?>
<tr><?php if (!$seperate) { ?><td><?php
			if ($label) {
				echo $this->formLabel($field) . ':';
			}
								?></td><?php } ?><td<?php echo ($seperate ? ' colspan="2"' : null) ?>><?php
										if (!empty($view)) {
											echo call_user_func_array(array(
												$this, $view
											), array(
												$field
											));
										}
																				 ?></td>
	</tr><?php
																						 echo $this->formElementErrors()->setMessageOpenFormat('<tr><div class="help-inline">')->setMessageSeparatorString('</div><div class="help-inline">')->setMessageCloseString('</div></tr>')->render($field);
		 ?>
<?php
	}
}
?>

</table>
<?php
echo $this->form()->closeTag();
?>
</div>