<div class="header"><div><?php echo $this->escapeHtml($this->translate($this->title)); ?></div></div>
<div class="content">
<?php
$form = $this->form;
?><table class="form">
<?php
$formLabel = $this->plugin('formLabel');
$rowspanCount = 1;
$rowspanTotal = 1;
$rowspanStatus = false;
foreach ($form->getElements() as $elements_key => $elements) {
	$field = $form->get($elements_key);
	if (is_object($field)) {
		$attributes = $field->getAttributes();
		$options = $field->getOptions();
		if (isset($attributes['rowspan']) && $attributes['rowspan'] > 0) {
			$rowspanTotal = $attributes['rowspan'];
			$rowspanStatus = true;
		}
		if ($rowspanCount == 1) {
?><tr<?php echo ($attributes['is_hidden'] ? ' style="display: none;"' : null) ?> <?php echo (isset($attributes['id']) ? 'id="' . $attributes['id'] . '"' : null); ?>>
<?php
		}
		if (isset($attributes['type']) || $attributes['class'] == 'selectdate') {
			if (!isset($attributes['type'])) {
				$attributes['type'] = '';
			}
			$elementRender = call_user_func_array(array(
					$this,
					'form' . ucfirst($attributes['element'])
			), array(
					$field
			));
			if ($attributes['type'] == 'seperator') {
?><td class="seperator" colspan="3">
<?php
				echo $elementRender;
?>
</td>
<?php
			} elseif ($attributes['type'] == 'submit' || $attributes['type'] == 'button') {
				if ($rowspanCount == 1) {
?><td></td>
<td class="field" colspan="2">
<?php
				}
?><span class="button">
<?php
				echo $elementRender;
?></span>
<?php
				$rowspanCount++;
				if ($rowspanCount > $rowspanTotal) {
?></td>
<?php
				}
			} else {
?><td class="label">
<?php
				if (!$attributes['not_show_label']) {
					echo $this->formLabel($field) . ':';
				}
?></td>
<td class="field">
<?php
				echo $elementRender;
?>
</td>
<td class="help"></td>
<?php
			}
			if (!$rowspanStatus || ($rowspanStatus && $rowspanCount > $rowspanTotal)) {
?></tr>
<?php
			}
		}
		if ($rowspanCount > $rowspanTotal) {
			$rowspanCount = 1;
			$rowspanTotal = 1;
			$rowspanStatus = false;
		}
	}
}
?></table>
</div>