<?php
$form = $this->form;
$elements = $form->getElements();
$total_element = count($elements);
if ($total_element > 0) {
	echo $this->form()->openTag($form) . "\n";
?><table class="form">
	<tr class="row"><?php
	$wallet_username = $form->get('wallet_username');
	$isRequire = $wallet_username->getAttribute('is_require');
					?><td class="label"><?php
						echo $this->formLabel($wallet_username) . '&nbsp;:' . ($isRequire ? '<span class="required">*</span>' : null);

										?></td><td class="element"><?php
											echo $this->formText($wallet_username);
																   ?></td><td></td>
	</tr>
	<tr class="row" id="wallet_username">
		<td></td>
		<td class="help" colspan="2">
		<div class="ui-widget"><div class="ui-state-active"></div></div>
		</td>
	</tr>
	<tr class="row"><?php
																	   $wallet_password = $form->get('wallet_password');
																	   $isRequire = $wallet_username->getAttribute('is_require');
					?><td class="label"><?php
						echo $this->formLabel($wallet_password) . '&nbsp;:' . ($isRequire ? '<span class="required">*</span>' : null);

										?></td><td class="element"><?php
											echo $this->formPassword($wallet_password);
																   ?></td><td></td>
	</tr>
	<tr class="row" id="wallet_password">
		<td></td>
		<td class="help" colspan="2">
		<div class="ui-widget"><div class="ui-state-active"></div></div>
		</td>
	</tr>
	<tr class="row"><?php
																	   $login_button = $form->get('button_login');
					?><td></td><td class="button" colspan="2"><?php
						echo $this->formButton($login_button);
															  ?></td>
	</tr>
	</table><?php
																  echo $this->form()->closeTag() . "\n";
															  }
			?>
			