<?php
$search = $this->search;
$searchdata = array ();
if (is_array ( $search ) && count ( $search ) > 0) {
	foreach ( $search as $searchvalue ) {
		$element = $searchvalue ['element'];
		$attributes = $element->getAttributes ();
		$elementRender = call_user_func_array ( array (
				$this,
				'form' . ucfirst ( $attributes ['type'] ) 
		), array (
				$element 
		) );
		$elementLabel = $this->formLabel ( $element ) . ': ';
		$searchdata [$searchvalue ['column']] ['label'] = $elementLabel . "\n";
		$searchdata [$searchvalue ['column']] ['input'] = $elementRender . "\n";
	}
}
?>
<form id="searchadvance">
	<table class="form">
		<tr>
			<td class="label"><?php echo $searchdata['user_username_from']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_username_from']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_username_to']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_username_to']['input']; ?></td>
			<td rowspan="7" style="width: auto;"></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_history_amount_in']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_amount_in']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_wallet_history_amount_out']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_amount_out']['input']; ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_history_ref_no']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_ref_no']['input']; ?></td>
			<td class="label"></td>
			<td class="field"></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_status_text']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_status_text']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_wallet_transaction_text']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_transaction_text']['input']; ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_type_from_text']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_type_from_text']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_wallet_type_to_text']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_type_to_text']['input']; ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_history_created_by']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_created_by']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_wallet_history_created_date_format']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_created_date_format']['input']; ?></td>
		</tr>
		<tr>
			<td class="label"><?php echo $searchdata['user_wallet_history_approved_by']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_approved_by']['input']; ?></td>
			<td class="label"><?php echo $searchdata['user_wallet_history_approved_date_format']['label']; ?></td>
			<td class="field"><?php echo $searchdata['user_wallet_history_approved_date_format']['input']; ?></td>
		</tr>
		<tr>
			<td colspan="5" style="text-align: center;"><button type="button"
					id="advancebutton" class="button">Search</button></td>
		</tr>
	</table>
</form>