<?php
header ( 'Cache-Control: no-cache, must-revalidate' );
header ( 'Expires: ' . $this->expire );
header ( 'Content-Type: text/css' );
$cache = $this->cache;
if (! $cache->start ( $this->key )) {
	$encryptKey = $this->key;
	foreach ( $this->css as $css => $status ) {
		$filepath = $css;
		if (file_exists ( $filepath ) && $status) {
			include $filepath;
			echo "\n";
			echo "\n";
		}
	}
	$cache->end ();
}