<?php
use Kernel\ServiceLocator;
use Zend\Cache\PatternFactory;

$currenturi = str_replace('http://', '', (array_key_exists('HTTP_REFERER', $_SERVER) ? $_SERVER['HTTP_REFERER'] : 'css'));
$currenturi = str_replace('https://', '', $currenturi);
$key = strtolower(str_replace('/', '_', $currenturi));

header('Cache-Control: no-cache, must-revalidate');
header('Expires: ' . $this->expire);
header('Content-Type: text/css');
$options = array(
		'options' => array(
			'storage' => array(
				'adapter' => array(
					'name' => 'filesystem', 'options' => array(
						'namespace' => 'css', 'namespace_separator' => '_', 'cache_dir' => 'Data/Cache', 'readable' => CACHE_ENABLE, 'writable' => CACHE_ENABLE,
					)
				)
			), 'cache_output' => true,
		)
);
$cache = PatternFactory::factory('output', $options['options']);
if (!$cache->start($key)) {
	foreach ($this->css as $css => $status) {
		if (file_exists(CORE_PATH . '/' . $css) && $status) {
			include(CORE_PATH . '/' . $css);
			echo "\n";
			echo "\n";
		}
	}
	$cache->end();
}
