<?php
use Zend\Cache\PatternFactory;

$currenturi = str_replace('http://', '', (array_key_exists('HTTP_REFERER', $_SERVER) ? $_SERVER['HTTP_REFERER'] : 'css'));
$currenturi = str_replace('https://', '', $currenturi);
$key = strtolower(str_replace('.', '_', str_replace('/', '_', $currenturi)));

header('Cache-Control: no-cache, must-revalidate');
header('Expires: ' . $this->expire);
header('Content-Type: text/x-component');
$cache = $this->cache;
if (!$cache->start($key)) {
	$filepath = $this->htc;
	if (file_exists($filepath)) {
		include $filepath;
	}
	$cache->end();
}
