<?php
header ( 'Cache-Control: no-cache, must-revalidate' );
header ( 'Expires: ' . $this->expire );
header ( 'Content-Type: application/x-javascript' );
$cache = $this->cache;
if (! $cache->start ( $this->key )) {
	$encryptKey = $this->key;
	foreach ( $this->javascript as $javascript => $status ) {
		$parameter = null;
		if (! is_bool ( $status ) && is_array ( $status )) {
			$parameter = $status ['parameter'];
			$status = $status ['status'];
		}
		$filepath = $javascript;
		if (file_exists ( $filepath ) && $status) {
			include $filepath;
			echo "\n";
			echo "\n";
		}
	}
	$cache->end ();
}

