<?php
use Kernel\ServiceLocator;
use Zend\Cache\PatternFactory;

$currenturi = str_replace('http://', '', (array_key_exists('HTTP_REFERER', $_SERVER) ? $_SERVER['HTTP_REFERER'] : 'javascript'));
$currenturi = str_replace('https://', '', $currenturi);
$key = strtolower(str_replace('/', '_', $currenturi));

header('Cache-Control: no-cache, must-revalidate');
header('Expires: ' . $this->expire);
header('Content-Type: application/x-javascript');
$options = array(
		'options' => array(
				'storage' => array(
						'adapter' => array(
								'name' => 'filesystem',
								'options' => array(
										'namespace' => 'javascript',
										'namespace_separator' => '_',
										'cache_dir' => 'Data/Cache',
										'readable' => CACHE_ENABLE,
										'writable' => CACHE_ENABLE,
								)
						)
				),
				'cache_output' => true,
		)
);
$cache = PatternFactory::factory('output', $options['options']);
if (!$cache->start($key)) {
	foreach ($this->javascript as $javascript => $status) {
		if (file_exists(CORE_PATH . '/' . $javascript) && $status) {
			include(CORE_PATH . '/' . $javascript);
			echo "\n";
			echo "\n";
		}
	}
	$cache->end();
}

